// Shared types for 10xCards application

// ============================================================================
// Database Models
// ============================================================================

export interface Flashcard {
  id: string;
  user_id: string;
  front: string; // Spanish word/phrase
  back: string; // Polish translation
  part_of_speech: string | null; // Optional part of speech
  leitner_box: 1 | 2 | 3; // Leitner box number
  review_due_at: string; // ISO timestamp
  ai_generated: boolean; // Whether generated by AI
  created_at: string; // ISO timestamp
  updated_at: string; // ISO timestamp
}

export interface User {
  id: string;
  email: string;
  created_at: string;
  updated_at: string;
}

// ============================================================================
// API Request/Response Types
// ============================================================================

// Auth
export interface RegisterRequest {
  email: string;
  password: string;
}

export interface LoginRequest {
  email: string;
  password: string;
}

export interface AuthResponse {
  user: User;
  session: {
    access_token: string;
    refresh_token: string;
    expires_at: number;
  };
}

// Flashcard Generation
export interface GenerateFlashcardsRequest {
  text: string;
  level?: 'A2' | 'B1' | 'B2';
}

export interface GeneratedFlashcard {
  front: string;
  back: string;
  part_of_speech?: string;
}

export interface GenerateFlashcardsResponse {
  flashcards: GeneratedFlashcard[];
}

// Flashcard CRUD
export interface CreateFlashcardRequest {
  front: string;
  back: string;
  part_of_speech?: string;
  ai_generated: boolean;
}

export interface BulkCreateFlashcardsRequest {
  flashcards: CreateFlashcardRequest[];
}

export interface UpdateFlashcardRequest {
  front?: string;
  back?: string;
  part_of_speech?: string;
}

export interface GetFlashcardsResponse {
  flashcards: Flashcard[];
}

export interface CreateFlashcardResponse {
  flashcard: Flashcard;
}

export interface BulkCreateFlashcardsResponse {
  count: number;
  flashcards: Flashcard[];
}

// Learning Session
export interface ReviewFlashcard {
  id: string;
  front: string;
  back: string;
  part_of_speech: string | null;
  leitner_box: 1 | 2 | 3;
}

export interface GetReviewFlashcardsResponse {
  flashcards: ReviewFlashcard[];
  count: number;
}

export interface ReviewFlashcardRequest {
  result: 'correct' | 'incorrect';
}

export interface ReviewFlashcardResponse {
  flashcard: {
    id: string;
    leitner_box: 1 | 2 | 3;
    review_due_at: string;
  };
}

// ============================================================================
// Error Types
// ============================================================================

export interface ApiError {
  error: string;
  code?: string;
  details?: unknown;
}

// ============================================================================
// Component Props Types
// ============================================================================

export interface FlashcardCardProps {
  flashcard: Flashcard;
  onEdit?: (flashcard: Flashcard) => void;
  onDelete?: (id: string) => void;
}

export interface FlashcardFormProps {
  onSubmit: (data: CreateFlashcardRequest) => void;
  isLoading?: boolean;
}

export interface GenerateFlashcardsFormProps {
  onGenerate: (data: GenerateFlashcardsRequest) => void;
  isLoading?: boolean;
}

export interface FlashcardProposalListProps {
  proposals: GeneratedFlashcard[];
  onEdit: (index: number, flashcard: GeneratedFlashcard) => void;
  onRemove: (index: number) => void;
  onAcceptAll: () => void;
}

export interface LearningSessionProps {
  flashcard: ReviewFlashcard;
  onReview: (result: 'correct' | 'incorrect') => void;
  isLoading?: boolean;
}

// ============================================================================
// State Management Types
// ============================================================================

export interface AuthState {
  user: User | null;
  isAuthenticated: boolean;
  isLoading: boolean;
}

export interface FlashcardsState {
  flashcards: Flashcard[];
  isLoading: boolean;
  error: string | null;
}

export interface GenerationState {
  proposals: GeneratedFlashcard[];
  isGenerating: boolean;
  error: string | null;
}

export interface LearningSessionState {
  currentFlashcard: ReviewFlashcard | null;
  remainingCount: number;
  completedCount: number;
  isLoading: boolean;
}

// ============================================================================
// Utility Types
// ============================================================================

export type LanguageLevel = 'A2' | 'B1' | 'B2';

export type LeitnerBox = 1 | 2 | 3;

export type PartOfSpeech =
  | 'rzeczownik'
  | 'czasownik'
  | 'przymiotnik'
  | 'przysłówek'
  | 'zaimek'
  | 'przyimek'
  | 'spójnik'
  | 'wykrzyknik'
  | 'fraza'
  | null;

// ============================================================================
// Constants
// ============================================================================

export const LANGUAGE_LEVELS: LanguageLevel[] = ['A2', 'B1', 'B2'];

export const LEITNER_BOXES: LeitnerBox[] = [1, 2, 3];

export const PARTS_OF_SPEECH: PartOfSpeech[] = [
  'rzeczownik',
  'czasownik',
  'przymiotnik',
  'przysłówek',
  'zaimek',
  'przyimek',
  'spójnik',
  'wykrzyknik',
  'fraza',
];

export const MAX_TEXT_LENGTH = 2000;

export const MAX_FLASHCARDS_PER_GENERATION = 20;

// Review intervals in milliseconds
export const REVIEW_INTERVALS = {
  BOX_1_TO_2: 24 * 60 * 60 * 1000, // 1 day
  BOX_2_TO_3: 3 * 24 * 60 * 60 * 1000, // 3 days
  BOX_3: 3 * 24 * 60 * 60 * 1000, // 3 days
} as const;

