// Shared types for 10xCards application

import { z } from 'zod';

// ============================================================================
// Database Models & DTOs
// ============================================================================

export interface Flashcard {
  id: string;
  user_id: string;
  front: string; // Spanish word/phrase
  back: string; // Polish translation
  part_of_speech: string | null; // Optional part of speech
  leitner_box: number; // Review level (1-5)
  review_due_at: string; // ISO timestamp
  ai_generated: boolean; // Whether generated by AI
  created_at: string; // ISO timestamp
  updated_at: string; // ISO timestamp
}

/**
 * DTO for a single flashcard item in a list.
 * Represents the data structure for the `GET /api/flashcards` response.
 */
export type FlashcardListItemDto = Pick<
  Flashcard,
  'id' | 'front' | 'back' | 'part_of_speech' | 'leitner_box' | 'review_due_at' | 'created_at'
>;

/**
 * DTO for a single, detailed flashcard view.
 */
export type FlashcardDetailDto = Flashcard;

/**
 * DTO for pagination details included in list responses.
 */
export type PaginationDto = {
  currentPage: number;
  pageSize: number;
  totalItems: number;
  totalPages: number;
};

/**
 * DTO for the response of the paginated list of flashcards.
 */
export type ListFlashcardsResponseDto = {
  data: FlashcardListItemDto[];
  pagination: PaginationDto;
};

/**
 * Command Model for creating a new flashcard manually.
 */
export type CreateFlashcardCommand = Pick<Flashcard, 'front' | 'back' | 'part_of_speech'>;

/**
 * DTO for the response after creating a flashcard.
 */
export type CreatedFlashcardDto = Pick<
  Flashcard,
  'id' | 'front' | 'back' | 'part_of_speech' | 'leitner_box' | 'review_due_at' | 'created_at'
>;

/**
 * Command Model for updating an existing flashcard.
 * All fields are optional to allow partial updates.
 */
export type UpdateFlashcardCommand = Partial<Pick<Flashcard, 'front' | 'back' | 'part_of_speech'>>;

/**
 * ViewModel for the FlashcardTable component state.
 * Manages the list of flashcards, pagination, loading and error states.
 */
export type FlashcardTableViewModel = {
  flashcards: FlashcardListItemDto[];
  pagination: PaginationDto;
  isLoading: boolean;
  error: string | null;
};

/**
 * Props for the FlashcardRow component.
 */
export interface FlashcardRowProps {
  flashcard: FlashcardListItemDto;
  onUpdate: (id: string, data: UpdateFlashcardCommand) => Promise<void>;
  onDelete: (id: string) => Promise<void>;
}

/**
 * Props for the Pagination component.
 */
export interface PaginationProps {
  currentPage: number;
  pageSize: number;
  totalItems: number;
  totalPages: number;
  onPageChange: (page: number) => void;
}

export interface User {
  id: string;
  email: string;
  created_at: string;
  updated_at: string;
}

// ============================================================================
// API Request/Response Types
// ============================================================================

// Auth
export interface RegisterRequest {
  email: string;
  password: string;
}

export interface LoginRequest {
  email: string;
  password: string;
}

export interface AuthResponse {
  user: User;
  session: {
    access_token: string;
    refresh_token: string;
    expires_at: number;
  };
}

// Flashcard Generation
export interface GenerateFlashcardsRequest {
  text: string;
  level?: 'A2' | 'B1' | 'B2';
}

export interface GeneratedFlashcard {
  front: string;
  back: string;
  part_of_speech?: string;
}

export interface GenerateFlashcardsResponse {
  flashcards: GeneratedFlashcard[];
}

// Flashcard CRUD
export interface CreateFlashcardRequest {
  front: string;
  back: string;
  part_of_speech?: string;
  ai_generated: boolean;
}

export interface BulkCreateFlashcardsRequest {
  flashcards: CreateFlashcardRequest[];
}

export interface UpdateFlashcardRequest {
  front?: string;
  back?: string;
  part_of_speech?: string;
}

export interface GetFlashcardsResponse {
  flashcards: Flashcard[];
}

export interface CreateFlashcardResponse {
  flashcard: Flashcard;
}

export interface BulkCreateFlashcardsResponse {
  count: number;
  flashcards: Flashcard[];
}

// Learning Session / Review
export interface ReviewFlashcard {
  id: string;
  front: string;
  back: string;
  part_of_speech: string | null;
  leitner_box: 1 | 2 | 3;
}

/**
 * DTO for a single card presented during a review session.
 */
export type ReviewCardDto = Pick<Flashcard, 'id' | 'front' | 'back' | 'part_of_speech'>;

/**
 * DTO for the entire set of cards in a review session.
 */
export type ReviewSessionDto = {
  cards: ReviewCardDto[];
};

/**
 * DTO for updating a card's review status.
 */
export type UpdateCardReviewDto = {
  flashcardId: string;
  knewIt: boolean;
};

export interface GetReviewFlashcardsResponse {
  flashcards: ReviewFlashcard[];
  count: number;
}

export interface ReviewFlashcardRequest {
  result: 'correct' | 'incorrect';
}

export interface ReviewFlashcardResponse {
  flashcard: {
    id: string;
    leitner_box: 1 | 2 | 3;
    review_due_at: string;
  };
}

// ============================================================================
// Error Types
// ============================================================================

export interface ApiError {
  error: string;
  code?: string;
  details?: unknown;
}

// ============================================================================
// Component Props Types
// ============================================================================

export interface FlashcardCardProps {
  flashcard: Flashcard;
  onEdit?: (flashcard: Flashcard) => void;
  onDelete?: (id: string) => void;
}

export interface FlashcardFormProps {
  onSubmit: (data: CreateFlashcardRequest) => void;
  isLoading?: boolean;
}

export interface GenerateFlashcardsFormProps {
  onGenerate: (data: GenerateFlashcardsRequest) => void;
  isLoading?: boolean;
}

export interface FlashcardProposalListProps {
  proposals: GeneratedFlashcard[];
  onEdit: (index: number, flashcard: GeneratedFlashcard) => void;
  onRemove: (index: number) => void;
  onAcceptAll: () => void;
}

export interface LearningSessionProps {
  flashcard: ReviewFlashcard;
  onReview: (result: 'correct' | 'incorrect') => void;
  isLoading?: boolean;
}

// ============================================================================
// State Management Types
// ============================================================================

export interface AuthState {
  user: User | null;
  isAuthenticated: boolean;
  isLoading: boolean;
}

export interface FlashcardsState {
  flashcards: Flashcard[];
  isLoading: boolean;
  error: string | null;
}

export interface GenerationState {
  proposals: GeneratedFlashcard[];
  isGenerating: boolean;
  error: string | null;
}

export interface LearningSessionState {
  currentFlashcard: ReviewFlashcard | null;
  remainingCount: number;
  completedCount: number;
  isLoading: boolean;
}

// ============================================================================
// Utility Types
// ============================================================================

export type LanguageLevel = 'A2' | 'B1' | 'B2';

// ============================================================================
// Enhanced Types for Template Compatibility
// ============================================================================

/**
 * Query parameters for flashcard list pagination and sorting.
 */
export interface FlashcardListQueryParams {
  page?: number;
  pageSize?: number;
  sortBy?: string;
  order?: 'asc' | 'desc';
}

/**
 * Props for the EditableCell component.
 * Manages inline editing of flashcard fields.
 */
export interface EditableCellProps {
  value: string | null;
  fieldName: keyof UpdateFlashcardCommand;
  onSave: (value: string) => Promise<void>;
  isEditable?: boolean;
}

/**
 * Local state for the EditableCell component.
 * Tracks editing mode, current value, validation errors and saving state.
 */
export interface EditableCellState {
  isEditing: boolean;
  currentValue: string;
  error: string | null;
  isSaving: boolean;
}

/**
 * State for AI generation functionality.
 */
export interface AiGenerationState {
  suggestions: AiSuggestionViewModel[];
  isGenerating: boolean;
  isImporting: boolean;
  error: string | null;
}

export type LeitnerBox = 1 | 2 | 3 | 4 | 5;

export type PartOfSpeech =
  | 'rzeczownik'
  | 'czasownik'
  | 'przymiotnik'
  | 'przysłówek'
  | 'zaimek'
  | 'przyimek'
  | 'spójnik'
  | 'wykrzyknik'
  | 'fraza'
  | null;

// ============================================================================
// Constants
// ============================================================================

export const LANGUAGE_LEVELS: LanguageLevel[] = ['A2', 'B1', 'B2'];

export const LEITNER_BOXES: LeitnerBox[] = [1, 2, 3, 4, 5];

export const PARTS_OF_SPEECH: PartOfSpeech[] = [
  'rzeczownik',
  'czasownik',
  'przymiotnik',
  'przysłówek',
  'zaimek',
  'przyimek',
  'spójnik',
  'wykrzyknik',
  'fraza',
];

export const MAX_TEXT_LENGTH = 2000;

export const MAX_FLASHCARDS_PER_GENERATION = 20;

// Review intervals in milliseconds
export const REVIEW_INTERVALS = {
  BOX_1_TO_2: 24 * 60 * 60 * 1000, // 1 day
  BOX_2_TO_3: 3 * 24 * 60 * 60 * 1000, // 3 days
  BOX_3: 3 * 24 * 60 * 60 * 1000, // 3 days
} as const;

// ============================================================================
// Additional ViewModels for New Features
// ============================================================================

/**
 * Represents a single AI-generated suggestion with editing capabilities
 */
export interface AiSuggestionViewModel {
  id: string;
  front: string;
  back: string;
  part_of_speech: string | null;
  isEditing: boolean;
  tempFront: string;
  tempBack: string;
  tempPartOfSpeech: string | null;
}

/**
 * ViewModel for manual flashcard creation form
 */
export interface ManualFormViewModel {
  front: string;
  back: string;
  part_of_speech: string | null;
  isSubmitting: boolean;
}

/**
 * Command for generating AI suggestions
 */
export interface GenerateSuggestionsCommand {
  text: string;
  level: 'b1' | 'b2' | 'c1';
}

/**
 * DTO for a single AI suggestion
 */
export interface AiSuggestion {
  id: string;
  front: string;
  back: string;
  part_of_speech: string | null;
}

/**
 * Response DTO for generate suggestions endpoint
 */
export interface GenerateSuggestionsResponseDto {
  suggestions: AiSuggestion[];
}

/**
 * Command for importing flashcards
 */
export interface ImportFlashcardsCommand {
  flashcards: Array<{
    front: string;
    back: string;
    part_of_speech?: string | null;
  }>;
  metrics: {
    generatedCount: number;
    importedCount: number;
  };
}

/**
 * Response DTO for import flashcards endpoint
 */
export interface ImportFlashcardsResponseDto {
  message: string;
  importedCount: number;
}

// ============================================================================
// Zod Schemas for AI Generation
// ============================================================================

/**
 * Zod schema for a single flashcard suggestion generated by the AI.
 * Used for validation of AI API responses.
 */
export const AiSuggestionSchema = z.object({
  front: z.string().describe('The front side of the flashcard (a word or phrase).'),
  back: z.string().describe('The back side of the flashcard (the translation or definition).'),
  part_of_speech: z.string().nullable().describe('The part of speech (e.g., noun, verb).'),
});

/**
 * Zod schema for the entire AI response containing flashcard suggestions.
 * Used for validation of AI API responses.
 */
export const GenerateSuggestionsResponseSchema = z.object({
  suggestions: z.array(AiSuggestionSchema).describe('An array of generated flashcard suggestions.'),
});

// ============================================================================
// Authentication Types
// ============================================================================

/**
 * Form data for user registration.
 * Represents the structure of data collected in the registration form.
 */
export type RegisterFormData = {
  email: string;
  password: string;
};

/**
 * Validation errors for registration form fields.
 * Maps field names to their corresponding error messages.
 */
export type RegisterFormErrors = {
  email?: string;
  password?: string;
};

/**
 * Complete state of the registration form component.
 * Manages form data, validation errors, loading state, and general errors.
 */
export type RegisterFormState = {
  formData: RegisterFormData;
  errors: RegisterFormErrors;
  isLoading: boolean;
  generalError: string | null;
};

// ============================================================================
// OpenRouter Service Types
// ============================================================================

/**
 * Configuration options for OpenRouter API completion requests.
 * Used to construct and send requests to the OpenRouter AI service.
 */
export type CompletionOptions = {
  /** System-level instructions defining the model's role and behavior */
  systemPrompt: string;
  /** User's specific query or input text */
  userPrompt: string;
  /** Name of the AI model to use (e.g., 'anthropic/claude-3.5-sonnet') */
  model: string;
  /** Zod schema defining the expected structure of the JSON response */
  responseSchema: z.ZodType;
  /** Optional model parameters for fine-tuning behavior */
  params?: {
    /** Controls randomness in responses (0.0 = deterministic, 1.0 = creative) */
    temperature?: number;
    /** Maximum number of tokens to generate in the response */
    max_tokens?: number;
  };
};
